version: '3.8'

services:
  django_app_emp:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/entrypoint.sh
    env_file:
      - ./.env
    volumes:
      - ./:/app
    environment:
      DJANGO_SETTINGS_MODULE: 'nomiweb.settings.production'
    ports:
      - "8081:8000"
    restart: always