version: '3'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: 'nomiweb.settings.production'
    ports:
      - "80:8000"