services:

  django_app_emp:
    build:
      context: .
      dockerfile: Dockerfile
    image: nomiweb-alfa:latest
    command: /app/entrypoint.sh
    env_file:
      - ./.en
    volumes:
      - ./:/app
    environment:
      DJANGO_SETTINGS_MODULE: 'nomiweb.settings.production'
    expose:
      - "8000"  # Este es el puerto interno expuesto dentro del contenedor
    ports:
      - "88:8000"
    restart: always
networks:
  default:
    external:
      name: proxy