version: '3'

services:
  django_app:
    build:
      command: /app/entrypoint.sh
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE: 'nomiweb.settings.production'
    ports:
      - "88:8000"
    restart: always