services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"   # Puerto HTTP
      - "443:443" # Puerto HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nomiweb.conf:/etc/nginx/conf.d/nomiweb.conf
      - ./certificates:/etc/nginx/ssl  # Certificados SSL
    depends_on:
      - django_app_emp
    restart: always

  django_app_emp:
    build:
      context: .
      dockerfile: Dockerfile
    image: nomiweb-alfa:latest
    command: /app/entrypoint.sh
    env_file:
      - ./.env
    volumes:
      - ./:/app
    environment:
      DJANGO_SETTINGS_MODULE: 'nomiweb.settings.production'
    expose:
      - "8000"  # Este es el puerto interno expuesto dentro del contenedor
    restart: always
networks:
  default:
    external:
      name: webnet